### ISSUE TITLE
struct data to Signal sends empty message on the wire

### ISSUE THREAD

**Issue by adityagodbole** [gilmour-libs/gilmour-e-go#8]
If the data to the Slot method is a struct, the message on the wire contains an empty hash in the "data" field.

**Comment by meson10** [comment]
That's because sending over the wire is done using "encoding/json"'s Marshal method. And unexported(lowe-case) fields of a struct are not Marshalled and I have not come across a way to include those in the marshalled string. This will have to be a limitation till then.
